import type { Metadata } from "next";
import { Geist_Mono, Quantico } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";

const geistSans = Quantico({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Games Catalog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <UserProvider>
                {children}
            </UserProvider>
        </body>
        </html>
    );
}
